/**
 * Feature branch policy (F-4.7).
 *
 * Every autonomous task works on a unique feature branch named:
 *
 *     fan-auto/<task-id>-<YYYYMMDD-HHmmss>
 *
 * Policy guarantees:
 * - Branch names are generated by a pure function — no I/O except the clock,
 *   which is injectable (`now`) for deterministic tests.
 * - The task identifier is sanitized into a safe git branch slug:
 *   unicode is folded to ASCII, spaces/slashes/special characters become
 *   dashes, the slug is lowercased, truncated and can never be empty.
 * - The generated name ALWAYS matches AUTONOMOUS_BRANCH_NAME_REGEX and can
 *   NEVER equal `main`/`master` (a slug that is exactly `main`/`master` is
 *   prefixed with `task-`, and the `fan-auto/` prefix + timestamp suffix make
 *   equality impossible anyway).
 *
 * Integration note: `AUTONOMOUS_BRANCH_POLICY` is the system-prompt rule text
 * for agents running in autonomous mode. It is exported here as the single
 * source of truth; actual injection into task messages happens later
 * (F-4.16 / scheduler config) — until then consumers prepend it to the task
 * message themselves.
 */

/** Regex validating autonomous branch names: fan-auto/<id>-<YYYYMMDD-HHmmss>. */
export const AUTONOMOUS_BRANCH_NAME_REGEX = /^fan-auto\/[\w-]+-\d{8}-\d{6}$/;

/** Prefix shared by all autonomous feature branches. */
export const BRANCH_PREFIX = "fan-auto";

/** Maximum length of the sanitized slug part of a branch name. */
export const MAX_SLUG_LENGTH = 50;

/** Protected branches — autonomous tasks must never target these. */
export const PROTECTED_BRANCHES: readonly string[] = ["main", "master"];

/** Fallback slug used when the task identifier sanitizes to nothing. */
const FALLBACK_SLUG = "task";

/** Minimal task shape needed for branch name generation. */
export interface BranchPolicyTask {
	/** Unique task identifier (preferred source for the branch slug). */
	id?: string;
	/** Human-readable task name (used when `id` is absent). */
	name?: string;
}

/**
 * System-prompt template enforcing the branch policy in autonomous mode.
 * Prepend this text to an autonomous task's message (see module docstring).
 */
export const AUTONOMOUS_BRANCH_POLICY = `Branch policy (autonomous mode):
- Create a unique feature branch named fan-auto/<task-id>-<YYYYMMDD-HHmmss> BEFORE any changes: git checkout -b fan-auto/<task-id>-<YYYYMMDD-HHmmss>
- Commit your work ONLY to this feature branch.
- NEVER commit or push directly to main/master — they are protected branches.
- When finished: git add -A && git commit -m "auto: <task summary>", then git push -u origin <branch>, then open a pull request: gh pr create --base main --head <branch> --title "auto: <task summary>" --body "Automated change generated by FAN agent."
- If branch creation, push or PR creation fails, report the failure in your final message instead of working around the policy.`;

/**
 * Sanitizes an arbitrary task identifier into a git-safe branch slug:
 * unicode → ASCII (diacritics stripped), lowercased, every run of characters
 * outside [a-z0-9_-] collapses to a single '-', edges trimmed, truncated to
 * MAX_SLUG_LENGTH. Never returns an empty string and never returns exactly
 * 'main'/'master' (prefixed with 'task-' in that case).
 */
export function sanitizeTaskId(raw: string): string {
	let slug = raw
		.normalize("NFKD")
		.replace(/[\u0300-\u036f]/g, "") // strip combining diacritical marks
		.toLowerCase()
		.replace(/[^a-z0-9_-]+/g, "-") // collapse invalid chars (incl. non-ASCII) into dashes
		.replace(/-{2,}/g, "-") // collapse runs of dashes
		.replace(/^[-_]+|[-_]+$/g, ""); // trim dashes/underscores at the edges

	if (slug.length > MAX_SLUG_LENGTH) {
		slug = slug.slice(0, MAX_SLUG_LENGTH).replace(/[-_]+$/g, "");
	}
	if (slug.length === 0) {
		slug = FALLBACK_SLUG;
	}
	if (PROTECTED_BRANCHES.includes(slug)) {
		slug = `${FALLBACK_SLUG}-${slug}`;
	}
	return slug;
}

/**
 * Formats a Date as YYYYMMDD-HHmmss in UTC. UTC is used deliberately so the
 * same `now()` value always produces the same timestamp regardless of the
 * host timezone.
 */
export function formatBranchTimestamp(date: Date): string {
	const pad = (n: number) => String(n).padStart(2, "0");
	return (
		`${date.getUTCFullYear()}${pad(date.getUTCMonth() + 1)}${pad(date.getUTCDate())}` +
		`-${pad(date.getUTCHours())}${pad(date.getUTCMinutes())}${pad(date.getUTCSeconds())}`
	);
}

/**
 * Generates the feature branch name for an autonomous task:
 * fan-auto/<sanitized-task-id>-<YYYYMMDD-HHmmss>.
 *
 * @param task Task object ({ id?, name? }) or a raw identifier string.
 * @param now  Clock injection (default: current time) — pass a fixed
 *             function in tests for deterministic output.
 */
export function generateBranchName(task: BranchPolicyTask | string, now: () => Date = () => new Date()): string {
	const raw = typeof task === "string" ? task : (task.id ?? task.name ?? "");
	return `${BRANCH_PREFIX}/${sanitizeTaskId(raw)}-${formatBranchTimestamp(now())}`;
}

/**
 * Validates a branch name against the autonomous naming convention.
 * Generated names always pass; use this to verify externally supplied names.
 */
export function isValidBranchName(name: string): boolean {
	return AUTONOMOUS_BRANCH_NAME_REGEX.test(name);
}
