import { beforeEach, describe, expect, it, vi } from "vitest";
import type { ExecFn, ExecResult } from "./gh-client.js";
import { createPullRequest, DEFAULT_BASE_BRANCH, detectBaseBranch, GH_CLI_NOT_FOUND_REASON } from "./gh-client.js";

const REPO = "/data/repos/my-project";
const BRANCH = "fan-auto/review-1-20260725-090000";
const PR_URL = "https://github.com/fan-network/my-project/pull/42";

type ExecMock = ReturnType<typeof vi.fn<ExecFn>>;

function ok(stdout = ""): ExecResult {
	return { stdout, stderr: "" };
}

function enoent(command: string): Error {
	const error = new Error(`spawn ${command} ENOENT`) as NodeJS.ErrnoException;
	error.code = "ENOENT";
	return error;
}

/**
 * Builds a mock exec that answers each command with the provided handlers
 * (matched by the first positional arg). Unmatched commands succeed silently.
 * Call order is recorded for order assertions.
 */
function buildExec(handlers: Record<string, (args: string[]) => ExecResult | Error>): {
	exec: ExecMock;
	calls: Array<{ command: string; args: string[] }>;
} {
	const calls: Array<{ command: string; args: string[] }> = [];
	const exec = vi.fn<ExecFn>(async (command, args) => {
		calls.push({ command, args: [...args] });
		const handler = handlers[command];
		if (!handler) return ok();
		const outcome = handler(args);
		if (outcome instanceof Error) throw outcome;
		return outcome;
	});
	return { exec, calls };
}

/** Mock exec covering the whole happy path (gh probe, HEAD detection, push, pr create). */
function happyPathExec(): { exec: ExecMock; calls: Array<{ command: string; args: string[] }> } {
	return buildExec({
		git: (args) => (args[0] === "symbolic-ref" ? ok("origin/main\n") : ok()),
		gh: (args) => (args[0] === "pr" ? ok(`${PR_URL}\n`) : ok("gh version 2.65.0\n")),
	});
}

let logSpy: ReturnType<typeof vi.spyOn>;

beforeEach(() => {
	logSpy = vi.spyOn(console, "log").mockImplementation(() => {});
});

describe("TC-F-4.8-1: PR is created with correct parameters", () => {
	it("runs gh pr create with exactly 4 flags and returns the PR URL", async () => {
		const { exec, calls } = happyPathExec();

		const result = await createPullRequest(
			{ repo: REPO, branch: BRANCH, taskName: "code-review" },
			{ exec, gitEnabled: true },
		);

		expect(result).toEqual({ prUrl: PR_URL, status: "created" });

		const prCreate = calls.find((c) => c.command === "gh" && c.args[0] === "pr");
		expect(prCreate).toBeDefined();
		expect(prCreate?.args).toEqual([
			"pr",
			"create",
			"--base",
			"main",
			"--head",
			BRANCH,
			"--title",
			"auto: code-review",
			"--body",
			"Automated fix generated by FAN agent.",
		]);
	});

	it("pushes the branch BEFORE creating the PR (order enforced)", async () => {
		const { exec, calls } = happyPathExec();

		await createPullRequest({ repo: REPO, branch: BRANCH, taskName: "code-review" }, { exec, gitEnabled: true });

		const sequence = calls.map((c) => `${c.command} ${c.args[0]}`);
		const pushIndex = sequence.indexOf("git push");
		const prIndex = sequence.indexOf("gh pr");
		expect(pushIndex).toBeGreaterThanOrEqual(0);
		expect(prIndex).toBeGreaterThan(pushIndex);

		const push = calls[pushIndex];
		expect(push.args).toEqual(["push", "-u", "origin", BRANCH]);
	});

	it("appends 'Closes #N' to the body when issueNumber is given", async () => {
		const { exec, calls } = happyPathExec();

		await createPullRequest(
			{ repo: REPO, branch: BRANCH, taskName: "code-review", issueNumber: 17 },
			{ exec, gitEnabled: true },
		);

		const prCreate = calls.find((c) => c.command === "gh" && c.args[0] === "pr");
		const body = prCreate?.args[prCreate.args.indexOf("--body") + 1];
		expect(body).toContain("Automated fix generated by FAN agent.");
		expect(body).toContain("Closes #17");
	});

	it("executes every command with the repo path as cwd", async () => {
		const exec = vi.fn<ExecFn>(async (command, args) => {
			if (command === "git" && args[0] === "symbolic-ref") return ok("origin/main\n");
			if (command === "gh" && args[0] === "pr") return ok(PR_URL);
			return ok();
		});

		await createPullRequest({ repo: REPO, branch: BRANCH, taskName: "code-review" }, { exec, gitEnabled: true });

		for (const call of exec.mock.calls) {
			expect(call[2]).toEqual({ cwd: REPO });
		}
	});
});

describe("TC-F-4.8-2: gh CLI unavailable → descriptive error, status partial", () => {
	it("returns status 'partial' with 'gh CLI not found' and runs nothing else", async () => {
		const { exec, calls } = buildExec({ gh: () => enoent("gh") });

		const result = await createPullRequest(
			{ repo: REPO, branch: BRANCH, taskName: "code-review" },
			{ exec, gitEnabled: true },
		);

		expect(result.status).toBe("partial");
		expect(result.reason).toBe(GH_CLI_NOT_FOUND_REASON);
		expect(result.prUrl).toBeUndefined();

		// only the probe ran — nothing was pushed, no pr create attempted
		expect(calls).toHaveLength(1);
		expect(calls[0]).toEqual({ command: "gh", args: ["--version"] });

		const logged = logSpy.mock.calls.map((c) => String(c[0])).join("\n");
		expect(logged).toContain("WARN");
		expect(logged).toContain("gh CLI not found");
	});
});

describe("git disabled (F-4.6 gate)", () => {
	it("returns status 'partial' with a warning and performs no external calls", async () => {
		const exec = vi.fn<ExecFn>();

		const result = await createPullRequest(
			{ repo: REPO, branch: BRANCH, taskName: "code-review" },
			{ exec, gitEnabled: false },
		);

		expect(result.status).toBe("partial");
		expect(result.reason).toContain("gitEnabled=false");
		expect(exec).not.toHaveBeenCalled();

		const logged = logSpy.mock.calls.map((c) => String(c[0])).join("\n");
		expect(logged).toContain("WARN");
	});
});

describe("push failure", () => {
	it("throws and never calls gh pr create", async () => {
		const { exec, calls } = buildExec({
			git: (args) => (args[0] === "push" ? new Error("remote: permission denied") : ok("origin/main\n")),
		});

		await expect(
			createPullRequest({ repo: REPO, branch: BRANCH, taskName: "code-review" }, { exec, gitEnabled: true }),
		).rejects.toThrow(/git push failed.*permission denied/);

		expect(calls.some((c) => c.command === "gh" && c.args[0] === "pr")).toBe(false);
	});
});

describe("base branch detection", () => {
	it("uses the remote HEAD branch (master) instead of the hardcoded default", async () => {
		const { exec, calls } = buildExec({
			git: (args) => (args[0] === "symbolic-ref" ? ok("origin/master\n") : ok()),
			gh: (args) => (args[0] === "pr" ? ok(PR_URL) : ok()),
		});

		await createPullRequest({ repo: REPO, branch: BRANCH, taskName: "code-review" }, { exec, gitEnabled: true });

		const prCreate = calls.find((c) => c.command === "gh" && c.args[0] === "pr");
		expect(prCreate?.args[prCreate.args.indexOf("--base") + 1]).toBe("master");
	});

	it("falls back to 'main' when remote HEAD detection fails", async () => {
		const { exec, calls } = buildExec({
			git: (args) =>
				args[0] === "symbolic-ref" ? new Error("fatal: ref refs/remotes/origin/HEAD is not a symbolic ref") : ok(),
			gh: (args) => (args[0] === "pr" ? ok(PR_URL) : ok()),
		});

		await createPullRequest({ repo: REPO, branch: BRANCH, taskName: "code-review" }, { exec, gitEnabled: true });

		const prCreate = calls.find((c) => c.command === "gh" && c.args[0] === "pr");
		expect(prCreate?.args[prCreate.args.indexOf("--base") + 1]).toBe("main");
	});

	it("detectBaseBranch trims whitespace and the origin/ prefix", async () => {
		const exec = vi.fn<ExecFn>(async () => ok("  origin/develop \n"));
		await expect(detectBaseBranch(REPO, exec)).resolves.toBe("develop");
	});

	it("detectBaseBranch falls back on empty output", async () => {
		const exec = vi.fn<ExecFn>(async () => ok(""));
		await expect(detectBaseBranch(REPO, exec)).resolves.toBe(DEFAULT_BASE_BRANCH);
	});
});

describe("gh pr create failure (non-ENOENT)", () => {
	it("throws a descriptive error after the push succeeded", async () => {
		const { exec, calls } = buildExec({
			git: (args) => (args[0] === "symbolic-ref" ? ok("origin/main\n") : ok()),
			gh: (args) => (args[0] === "pr" ? new Error("no commits between main and head") : ok()),
		});

		await expect(
			createPullRequest({ repo: REPO, branch: BRANCH, taskName: "code-review" }, { exec, gitEnabled: true }),
		).rejects.toThrow(/gh pr create failed.*no commits between main and head/);

		// push DID run before the failure
		expect(calls.some((c) => c.command === "git" && c.args[0] === "push")).toBe(true);
	});
});
