// packages/coding-agent/src/cli/init-wizard.ts
import { createInterface } from "node:readline";
import { mkdirSync, writeFileSync, existsSync, readFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { getAgentDir, getModelsPath, getSettingsPath, APP_NAME, VERSION } from "../config.js";

const PROVIDERS = [
	{ name: "OpenAI", envVar: "OPENAI_API_KEY", models: ["gpt-4o", "gpt-4o-mini", "o1", "o3-mini"] },
	{ name: "Anthropic", envVar: "ANTHROPIC_API_KEY", models: ["claude-sonnet-4-20250514", "claude-opus-4-20250514", "claude-haiku-4-20250414"] },
	{ name: "Google", envVar: "GOOGLE_API_KEY", models: ["gemini-2.5-pro", "gemini-2.5-flash", "gemini-2.0-flash"] },
	{ name: "Groq", envVar: "GROQ_AFAN_KEY", models: ["llama-3.3-70b-versatile", "llama-3.1-8b-instant"] },
	{ name: "xAI", envVar: "XAI_AFAN_KEY", models: ["grok-3", "grok-3-mini"] },
	{ name: "Mistral", envVar: "MISTRAL_AFAN_KEY", models: ["mistral-large-latest", "mistral-medium-latest"] },
	{ name: "OpenRouter", envVar: "OPENROUTER_AFAN_KEY", models: ["openrouter/auto"] },
	{ name: "GitHub Copilot", envVar: "COPILOT_GITHUB_TOKEN", models: ["gpt-4o", "claude-sonnet-4"] },
];

function createRL(): ReturnType<typeof createInterface> {
	return createInterface({ input: process.stdin, output: process.stdout });
}

function question(rl: ReturnType<typeof createInterface>, prompt: string): Promise<string> {
	return new Promise((resolve) => rl.question(prompt, resolve));
}

export async function runInitWizard(): Promise<void> {
	const rl = createRL();

	console.log(`\n🚀 ${APP_NAME} v${VERSION} — Setup Wizard\n`);

	// Step 1: Check prerequisites
	console.log("Checking prerequisites...");
	const nodeVersion = process.versions.node;
	const major = parseInt(nodeVersion.split(".")[0], 10);
	if (major < 20) {
		console.log(`❌ Node.js v${nodeVersion} detected. Version 20+ required.`);
		rl.close();
		process.exit(1);
	}
	console.log(`  ✅ Node.js v${nodeVersion}`);

	const agentDir = getAgentDir();
	if (!existsSync(agentDir)) {
		mkdirSync(agentDir, { recursive: true });
		console.log(`  ✅ Created agent directory: ${agentDir}`);
	} else {
		console.log(`  ✅ Agent directory: ${agentDir}`);
	}

	// Step 2: Provider selection
	console.log("\n📋 Select AI provider(s) to configure:");
	console.log("   (Enter numbers separated by commas, e.g. 1,3)");

	for (let i = 0; i < PROVIDERS.length; i++) {
		const p = PROVIDERS[i];
		const hasKey = process.env[p.envVar] ? " [configured]" : "";
		console.log(`   ${i + 1}. ${p.name}${hasKey}`);
	}

	const providerInput = await question(rl, "\n   Provider(s) [1]: ");
	const providerIndices = providerInput.trim()
		? providerInput.split(",").map(s => parseInt(s.trim(), 10) - 1).filter(i => i >= 0 && i < PROVIDERS.length)
		: [0]; // default: OpenAI

	if (providerIndices.length === 0) {
		console.log("❌ No providers selected.");
		rl.close();
		process.exit(1);
	}

	// Step 3: Collect API keys
	console.log("\n🔑 Enter API keys (press Enter to skip if already set):");
	const envVars: Record<string, string> = {};

	for (const idx of providerIndices) {
		const provider = PROVIDERS[idx];
		if (process.env[provider.envVar]) {
			console.log(`   ✅ ${provider.name}: already set (${provider.envVar})`);
			envVars[provider.envVar] = "";
		} else {
			const key = await question(rl, `   ${provider.name} (${provider.envVar}): `);
			if (key.trim()) {
				envVars[provider.envVar] = key.trim();
			}
		}
	}

	// Step 4: Default model selection
	const firstProvider = PROVIDERS[providerIndices[0]];
	console.log(`\n🤖 Select default model for ${firstProvider.name}:`);
	for (let i = 0; i < firstProvider.models.length; i++) {
		console.log(`   ${i + 1}. ${firstProvider.models[i]}`);
	}
	const modelInput = await question(rl, "\n   Model [1]: ");
	const modelIdx = parseInt(modelInput.trim() || "1", 10) - 1;
	const selectedModel = firstProvider.models[modelIdx >= 0 && modelIdx < firstProvider.models.length ? modelIdx : 0];

	// Step 5: Generate .env file
	const envPath = resolve(process.cwd(), ".env");
	let envContent = `# ${APP_NAME.toUpperCase()} Runtime Configuration\n# Generated by ${APP_NAME} init\n\n`;

	for (const [varName, value] of Object.entries(envVars)) {
		if (value) {
			envContent += `${varName}=${value}\n`;
		}
	}

	if (existsSync(envPath)) {
		const overwrite = await question(rl, `\n📄 .env file already exists. Overwrite? [y/N]: `);
		if (overwrite.toLowerCase() === "y") {
			writeFileSync(envPath, envContent);
			console.log("  ✅ Updated .env");
		} else {
			// Append new vars that don't exist
			const existing = readFileSync(envPath, "utf-8");
			let appended = false;
			for (const [varName, value] of Object.entries(envVars)) {
				if (value && !existing.includes(varName)) {
					writeFileSync(envPath, `\n${varName}=${value}\n`, { flag: "a" });
					appended = true;
				}
			}
			console.log(appended ? "  ✅ Appended new keys to .env" : "  ℹ️  No new keys to add");
		}
	} else {
		writeFileSync(envPath, envContent);
		console.log("  ✅ Created .env");
	}

	// Step 6: Generate settings.json
	const settingsPath = getSettingsPath();
	const settings = {
		defaultProvider: firstProvider.name.toLowerCase().replace(/\s+/g, "-"),
		defaultModel: selectedModel,
		theme: "dark",
		quietStartup: false,
	};

	if (existsSync(settingsPath)) {
		console.log(`  ℹ️  Global settings already exist at ${settingsPath}`);
		const overwrite = await question(rl, "  Overwrite? [y/N]: ");
		if (overwrite.toLowerCase() === "y") {
			writeFileSync(settingsPath, JSON.stringify(settings, null, 2));
			console.log("  ✅ Updated global settings");
		}
	} else {
		writeFileSync(settingsPath, JSON.stringify(settings, null, 2));
		console.log(`  ✅ Created global settings: ${settingsPath}`);
	}

	// Step 7: Summary
	console.log("\n✨ Setup complete!\n");
	console.log("  Configuration:");
	console.log(`    Provider: ${firstProvider.name}`);
	console.log(`    Model: ${selectedModel}`);
	console.log(`    Env file: ${envPath}`);
	console.log(`    Settings: ${settingsPath}`);
	console.log("\n  Next steps:");
	console.log("    fna                        Start interactive mode");
	console.log("    fna --mode server          Start with API & dashboard");
	console.log("    fna doctor                 Run diagnostics\n");

	rl.close();
}
