// packages/coding-agent/src/cli/init-wizard.ts

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { createInterface } from "node:readline";
import { getWizardProviders, isProviderConfigured } from "@seaagents/fan-ai";
import { APP_NAME, getAgentDir, getEnvPath, getModelsPath, getSettingsPath, VERSION } from "../config.js";

const WIZARD_PROVIDERS = getWizardProviders();

function createRL(): ReturnType<typeof createInterface> {
	return createInterface({ input: process.stdin, output: process.stdout });
}

function question(rl: ReturnType<typeof createInterface>, prompt: string): Promise<string> {
	return new Promise((resolve) => rl.question(prompt, resolve));
}

export async function runInitWizard(): Promise<void> {
	const rl = createRL();

	console.log(`\n🚀 ${APP_NAME} v${VERSION} — Setup Wizard\n`);

	// Step 1: Check prerequisites
	console.log("Checking prerequisites...");
	const nodeVersion = process.versions.node;
	const major = parseInt(nodeVersion.split(".")[0], 10);
	if (major < 20) {
		console.log(`❌ Node.js v${nodeVersion} detected. Version 20+ required.`);
		rl.close();
		process.exit(1);
	}
	console.log(`  ✅ Node.js v${nodeVersion}`);

	const agentDir = getAgentDir();
	if (!existsSync(agentDir)) {
		mkdirSync(agentDir, { recursive: true });
		console.log(`  ✅ Created agent directory: ${agentDir}`);
	} else {
		console.log(`  ✅ Agent directory: ${agentDir}`);
	}

	// Step 2: Provider selection
	console.log("\n📋 Select AI provider(s) to configure:");
	console.log("   (Enter numbers separated by commas, e.g. 1,3)");

	for (let i = 0; i < WIZARD_PROVIDERS.length; i++) {
		const { id, meta } = WIZARD_PROVIDERS[i];
		const hasKey = isProviderConfigured(id) ? " [configured]" : "";
		console.log(`   ${i + 1}. ${meta.displayName}${hasKey}`);
	}

	const providerInput = await question(rl, "\n   Provider(s) [1]: ");
	const providerIndices = providerInput.trim()
		? providerInput
				.split(",")
				.map((s) => parseInt(s.trim(), 10) - 1)
				.filter((i) => i >= 0 && i < WIZARD_PROVIDERS.length)
		: [0]; // default: OpenAI

	if (providerIndices.length === 0) {
		console.log("❌ No providers selected.");
		rl.close();
		process.exit(1);
	}

	// Step 3: Collect API keys
	console.log("\n🔑 Enter API keys (press Enter to skip if already set):");
	const envVars: Record<string, string> = {};

	for (const idx of providerIndices) {
		const { id, meta } = WIZARD_PROVIDERS[idx];
		if (isProviderConfigured(id)) {
			console.log(`   ✅ ${meta.displayName}: already set (${meta.primaryEnvVar})`);
			envVars[meta.primaryEnvVar] = "";
		} else {
			const key = await question(rl, `   ${meta.displayName} (${meta.primaryEnvVar}): `);
			if (key.trim()) {
				envVars[meta.primaryEnvVar] = key.trim();
			}
		}
	}

	// Step 4: Default model selection
	const firstProvider = WIZARD_PROVIDERS[providerIndices[0]];
	console.log(`\n🤖 Select default model for ${firstProvider.meta.displayName}:`);
	for (let i = 0; i < firstProvider.meta.wizardModels.length; i++) {
		console.log(`   ${i + 1}. ${firstProvider.meta.wizardModels[i]}`);
	}
	const modelInput = await question(rl, "\n   Model [1]: ");
	const modelIdx = parseInt(modelInput.trim() || "1", 10) - 1;
	const selectedModel =
		firstProvider.meta.wizardModels[
			modelIdx >= 0 && modelIdx < firstProvider.meta.wizardModels.length ? modelIdx : 0
		];

	// Step 5: Generate .env file (global location)
	const envPath = getEnvPath();
	let envContent = `# ${APP_NAME.toUpperCase()} Runtime Configuration\n# Generated by ${APP_NAME} init\n\n`;

	for (const [varName, value] of Object.entries(envVars)) {
		if (value) {
			envContent += `${varName}=${value}\n`;
		}
	}

	if (existsSync(envPath)) {
		const overwrite = await question(rl, `\n📄 .env file already exists. Overwrite? [y/N]: `);
		if (overwrite.toLowerCase() === "y") {
			writeFileSync(envPath, envContent);
			console.log("  ✅ Updated .env");
		} else {
			// Append new vars that don't exist
			const existing = readFileSync(envPath, "utf-8");
			let appended = false;
			for (const [varName, value] of Object.entries(envVars)) {
				if (value && !existing.includes(varName)) {
					writeFileSync(envPath, `\n${varName}=${value}\n`, { flag: "a" });
					appended = true;
				}
			}
			console.log(appended ? "  ✅ Appended new keys to .env" : "  ℹ️  No new keys to add");
		}
	} else {
		writeFileSync(envPath, envContent);
		console.log("  ✅ Created .env");
	}

	// Step 6: Generate settings.json
	const settingsPath = getSettingsPath();
	const settings = {
		defaultProvider: firstProvider.id,
		defaultModel: selectedModel,
		theme: "dark",
		quietStartup: false,
	};

	if (existsSync(settingsPath)) {
		console.log(`  ℹ️  Global settings already exist at ${settingsPath}`);
		const overwrite = await question(rl, "  Overwrite? [y/N]: ");
		if (overwrite.toLowerCase() === "y") {
			writeFileSync(settingsPath, JSON.stringify(settings, null, 2));
			console.log("  ✅ Updated global settings");
		}
	} else {
		writeFileSync(settingsPath, JSON.stringify(settings, null, 2));
		console.log(`  ✅ Created global settings: ${settingsPath}`);
	}

	// Step 7: Summary
	console.log("\n✨ Setup complete!\n");
	console.log("  Configuration:");
	console.log(`    Provider: ${firstProvider.meta.displayName}`);
	console.log(`    Model: ${selectedModel}`);
	console.log(`    Env file: ${envPath}`);
	console.log(`    Settings: ${settingsPath}`);
	console.log("\n  Next steps:");
	console.log("    fan                        Start interactive mode");
	console.log("    fan --web                  Start with dashboard (opens browser)");
	console.log("    fan --mode server          Start API server only");
	console.log("    fan doctor                 Run diagnostics\n");

	rl.close();
}
